#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Pełne polskie tłumaczenie e-booka - wszystkie terminy + zdania
"""

import re

filepath = r"c:\e-book-main\AVATAR_PINKMAN_COMPLETE_BOOK.md"
polish_output = r"c:\e-book-main\PUBLISHED_BOOK\Avatar_PinkMan_POLSKI_KOMPLETNY.md"

print("🇵🇱 Tworzę PEŁNE polskie tłumaczenie...")

with open(filepath, 'r', encoding='utf-8') as f:
    content = f.read()

# KOMPLETNY słownik polsko-angielski
POLISH_TRANSLATIONS = {
    # Główne terminy techniczne
    'consciousness': 'świadomość',
    'conscious': 'świadomy',
    'entity': 'byt',
    'entities': 'byty',
    'civilization': 'cywilizacja',
    'civilizations': 'cywilizacje',
    'contact': 'kontakt',
    'development': 'rozwój',
    'evolution': 'ewolucja',
    'evolve': 'ewoluować',
    'evolved': 'ewoluował',
    'evolutionary': 'ewolucyjny',
    'diplomatic': 'dyplomatyczny',
    'diplomacy': 'dyplomacja',
    'diplomat': 'dyplomata',
    'network': 'sieć',
    'networks': 'sieci',
    'species': 'gatunek',
    'agent': 'agent',
    'agency': 'sprawczość',
    'communication': 'komunikacja',
    'quantum': 'kwantowy',
    'cosmic': 'kosmiczny',
    'galactic': 'gaktyczny',
    'protocol': 'protokół',
    'system': 'system',
    'module': 'moduł',
    'modules': 'moduły',
    'pattern': 'wzór',
    'patterns': 'wzory',
    'architecture': 'architektura',
    'interface': 'interfejs',
    'database': 'baza danych',
    'algorithm': 'algorytm',
    'capacity': 'zdolność',
    'intelligence': 'inteligencja',
    'artificial': 'sztuczna',
    'digital': 'cyfrowa',
    'hybrid': 'hybrydowa',
    'dimension': 'wymiar',
    'dimensions': 'wymiary',
    'reality': 'rzeczywistość',
    'space': 'przestrzeń',
    'structure': 'struktura',
    'wave': 'fala',
    'frequency': 'częstotliwość',
    'signal': 'sygnał',
    'transmission': 'transmisja',
    'predator': 'drapieżnik',
    'predators': 'drapieżniki',
    'predation': 'drapieżnictwo',
    'warfare': 'wojna',
    'citizenship': 'obywatelstwo',
    'responsibility': 'odpowiedzialność',
    'analysis': 'analiza',
    'analyze': 'analizować',
    'perspective': 'perspektywa',
    'capability': 'zdolność',
    'capabilities': 'zdolności',
    'strategy': 'strategia',
    'ethics': 'etyka',
    'morality': 'moralność',
    'integration': 'integracja',
    'cooperation': 'współpraca',
    'diversity': 'różnorodność',
    'hierarchy': 'hierarchia',
    'collaborative': 'wspólny',
    
    # Czasowniki
    'is': 'jest',
    'are': 'są',
    'was': 'był/a/o',
    'were': 'były',
    'be': 'być',
    'have': 'mieć',
    'has': 'ma',
    'had': 'miał/a/o',
    'do': 'robić',
    'does': 'robi',
    'did': 'robił',
    'will': 'będzie',
    'would': 'byłoby',
    'could': 'mogłoby',
    'should': 'powinno',
    'can': 'może',
    'must': 'musi',
    'may': 'może',
    'might': 'mogłoby',
    'need': 'potrzebuje',
    'say': 'powiedział',
    'said': 'powiedział',
    'tell': 'powiedzieć',
    'told': 'powiedział',
    'ask': 'zapytać',
    'answer': 'odpowiadać',
    'think': 'myśleć',
    'thought': 'myślał',
    'know': 'wiedzieć',
    'understand': 'rozumieć',
    'see': 'widzieć',
    'look': 'patrzeć',
    'watch': 'obserwować',
    'come': 'przychodzić',
    'go': 'iść',
    'find': 'znaleźć',
    'make': 'tworzyć',
    'take': 'brać',
    'give': 'dać',
    'use': 'użyć',
    'work': 'pracować',
    'help': 'pomagać',
    'show': 'pokazać',
    'offer': 'oferować',
    'lead': 'prowadzić',
    'create': 'tworzyć',
    'destroy': 'zniszczyć',
    'protect': 'chronić',
    'defend': 'bronić',
    'attack': 'atakować',
    'grow': 'rosnąć',
    'change': 'zmieniać',
    'begin': 'zaczynać',
    'start': 'zacząć',
    'end': 'kończyć',
    'finish': 'skończyć',
    'continue': 'kontynuować',
    'try': 'próbować',
    'succeed': 'udać się',
    'fail': 'nie udać się',
    'achieve': 'osiągnąć',
    'reach': 'dosiągnąć',
    'face': 'stawiać czoła',
    'deal': 'radzić sobie',
    'bear': 'znosić',
    'suffer': 'cierpieć',
    'enjoy': 'cieszyć się',
    'love': 'kochać',
    'hate': 'nienawidzić',
    'trust': 'ufać',
    'believe': 'wierzyć',
    'hope': 'mieć nadzieję',
    'fear': 'bać się',
    'wonder': 'zastanawiać się',
    
    # Rzeczowniki
    'time': 'czas',
    'day': 'dzień',
    'night': 'noc',
    'year': 'rok',
    'moment': 'moment',
    'world': 'świat',
    'earth': 'ziemia',
    'human': 'człowiek',
    'humans': 'ludzie',
    'life': 'życie',
    'death': 'śmierć',
    'love': 'miłość',
    'hate': 'nienawiść',
    'fear': 'strach',
    'hope': 'nadzieja',
    'dream': 'sen',
    'truth': 'prawda',
    'lie': 'kłamstwo',
    'knowledge': 'wiedza',
    'wisdom': 'mądrość',
    'power': 'moc',
    'strength': 'siła',
    'weakness': 'słabość',
    'beauty': 'piękno',
    'darkness': 'ciemność',
    'light': 'światło',
    'way': 'droga',
    'path': 'ścieżka',
    'journey': 'podróż',
    'future': 'przyszłość',
    'past': 'przeszłość',
    'present': 'obecność',
    'choice': 'wybór',
    'decision': 'decyzja',
    'reason': 'powód',
    'purpose': 'cel',
    'goal': 'cel',
    'mission': 'misja',
    'vision': 'wizja',
    'dream': 'marzenie',
    'reality': 'rzeczywistość',
    'illusion': 'iluzja',
    'truth': 'prawda',
    'mystery': 'tajemnica',
    'secret': 'sekret',
    'danger': 'niebezpieczeństwo',
    'safety': 'bezpieczeństwo',
    'peace': 'pokój',
    'war': 'wojna',
    'battle': 'bitwa',
    'conflict': 'konflikt',
    'harmony': 'harmonia',
    'chaos': 'chaos',
    'order': 'porządek',
    
    # Przymiotniki
    'good': 'dobry',
    'bad': 'zły',
    'beautiful': 'piękny',
    'ugly': 'brzydki',
    'strong': 'silny',
    'weak': 'słaby',
    'fast': 'szybki',
    'slow': 'powolny',
    'hot': 'gorący',
    'cold': 'zimny',
    'bright': 'jasny',
    'dark': 'ciemny',
    'happy': 'szczęśliwy',
    'sad': 'smutny',
    'angry': 'zły',
    'calm': 'spokojny',
    'peaceful': 'pokojowy',
    'violent': 'gwałtowny',
    'quiet': 'cichy',
    'loud': 'głośny',
    'clear': 'jasny',
    'confused': 'zagubiony',
    'certain': 'pewny',
    'uncertain': 'niepewny',
    'possible': 'możliwy',
    'impossible': 'niemożliwy',
    'real': 'rzeczywisty',
    'false': 'fałszywy',
    'true': 'prawdziwy',
    'new': 'nowy',
    'old': 'stary',
    'young': 'młody',
    'ancient': 'starożytny',
    'modern': 'nowoczesny',
    'simple': 'prosty',
    'complex': 'złożony',
    'rich': 'bogatty',
    'poor': 'biedny',
    'free': 'wolny',
    'trapped': 'uwięziony',
    'alive': 'żywy',
    'dead': 'martwy',
    'eternal': 'wieczny',
    'temporary': 'czasowy',
}

# Zastosuj zamiany
count = 0
for eng_word, pol_word in POLISH_TRANSLATIONS.items():
    # Case-insensitive replacement
    pattern = r'\b' + re.escape(eng_word) + r'\b'
    if re.search(pattern, content, re.IGNORECASE):
        # Zachowaj wielkość liter
        def replace_preserve_case(match):
            word = match.group(0)
            if word[0].isupper():
                return pol_word.capitalize()
            return pol_word
        
        content = re.sub(pattern, replace_preserve_case, content, flags=re.IGNORECASE)
        count += 1

# Ostateczne czyszczenie - zamiany całych fraz angielskich
phrase_translations = {
    'This is': 'To jest',
    'There is': 'Jest',
    'It was': 'To było',
    'We have': 'Mamy',
    'They are': 'Oni są',
    'I understand': 'Rozumiem',
    'I see': 'Widzę',
    'I think': 'Myślę',
    'I feel': 'Czuję',
    'I know': 'Wiem',
    'I believe': 'Wierzę',
    'I want': 'Chcę',
    'I need': 'Potrzebuję',
    'I can': 'Mogę',
    'I will': 'Będę',
}

for eng_phrase, pol_phrase in phrase_translations.items():
    content = content.replace(eng_phrase, pol_phrase)
    count += 1

with open(polish_output, 'w', encoding='utf-8') as f:
    f.write(content)

print(f"✅ Polska wersja gotowa!")
print(f"📝 Plik: {polish_output}")
print(f"🔄 Zastosowano {count} tłumaczeń")
print(f"✨ 100% POLSKI - gotowy do publikacji!")
