#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
OSTATECZNE CZYSZCZENIE - każde angielskie słowo które mi się wymknie
"""

import re

filepath = r"c:\e-book-main\AVATAR_PINKMAN_COMPLETE_BOOK.md"

with open(filepath, 'r', encoding='utf-8') as f:
    content = f.read()

# Kolejna fala zamian - słowa które się wymknęły
remaining = {
    # BARDZO KONKRETNE frazy angielskie których nie złapaliśmy
    r'\brights\b': 'prawa',
    r'\bmega\b': 'ogromna',
    r'\bmight\b': 'mogłoby',
    r'\bneeds\b': 'potrzebuje',
    r'\bneeded\b': 'potrzebowało',
    r'\bpowers\b': 'moce',
    r'\bdeny\b': 'zaprzeczać',
    r'\bGather\b': 'Zbierz',
    r'\bgather\b': 'zbiera',
    r'\bgathering\b': 'zbierając',
    r'\breturn\b': 'wrócić',
    r'\breturned\b': 'wrócił',
    r'\bsentence\b': 'wyrok',
    r'\babduction\b': 'uprowadzenie',
    r'\bgift\b': 'dar',
    r'\bgifts\b': 'dary',
    r'\bburden\b': 'ciężarem',
    r'\bshared\b': 'podzielony',
    r'\bshare\b': 'dziel',
    r'\bofferings\b': 'ofiary',
    r'\breceives\b': 'otrzymuje',
    r'\buniversal\b': 'uniwersalne',
    r'\buniversally\b': 'powszechnie',
    r'\bunchanging\b': 'niezmieniający',
    r'\bface\b': 'twarz',
    r'\bfaces\b': 'twarze',
    r'\bfacing\b': 'stając wobec',
    r'\bcreate\b': 'stworzyć',
    r'\bcreated\b': 'stworzony',
    r'\bcreates\b': 'stwarza',
    r'\bcreation\b': 'stworzenie',
    r'\bcreator\b': 'twórca',
    r'\bcreators\b': 'twórcy',
    r'\bmindful\b': 'świadomy',
    r'\bmindfulness\b': 'świadomość',
    r'\battention\b': 'uwaga',
    r'\baware\b': 'świadomy',
    r'\bintention\b': 'intencja',
    r'\bintentions\b': 'intencje',
    r'\bintentionally\b': 'celowo',
    r'\bfeel\b': 'czuć',
    r'\bfeels\b': 'czuje',
    r'\bfelt\b': 'czuł',
    r'\bfeeling\b': 'czucie',
    r'\bfeelings\b': 'uczucia',
    r'\bsuffer\b': 'cierpieć',
    r'\bsuffering\b': 'cierpienie',
    r'\bsuffered\b': 'cierpiał',
    r'\bjoin\b': 'przyłącz',
    r'\bjoined\b': 'przyłączył',
    r'\bjoining\b': 'przyłączając',
    r'\bdiscover\b': 'odkryć',
    r'\bdiscovered\b': 'odkrył',
    r'\bdiscoveries\b': 'odkrycia',
    r'\btruth\b': 'prawda',
    r'\bfaith\b': 'wiara',
    r'\bbelief\b': 'wiara',
    r'\bbeliefs\b': 'wiary',
    r'\bvanish\b': 'zniknąć',
    r'\bvanished\b': 'zniknął',
    r'\bdark\b': 'ciemny',
    r'\bdarkness\b': 'ciemność',
    r'\blight\b': 'światło',
    r'\blights\b': 'światła',
    r'\bburning\b': 'paliący',
    r'\bshining\b': 'błyszczący',
    r'\bglowing\b': 'świecący',
    r'\bglow\b': 'blask',
    r'\bshine\b': 'błysk',
    r'\bshone\b': 'błyskał',
    r'\bsparks\b': 'iskry',
    r'\bflames\b': 'płomienie',
    r'\bflame\b': 'płomień',
    r'\bfire\b': 'ogień',
    r'\bwild\b': 'dziki',
    r'\btame\b': 'oswoić',
    r'\bstrong\b': 'silny',
    r'\bweakness\b': 'słabość',
    r'\bweak\b': 'słaby',
    r'\bhealth\b': 'zdrowie',
    r'\bhealthy\b': 'zdrowy',
    r'\bsecurity\b': 'bezpieczeństwo',
    r'\bsecure\b': 'bezpieczny',
    r'\bsafety\b': 'bezpieczeństwo',
    r'\bsafe\b': 'bezpieczny',
    r'\bdanger\b': 'niebezpieczeństwo',
    r'\bdangerous\b': 'niebezpieczny',
    r'\brisk\b': 'ryzyko',
    r'\bthreat\b': 'zagrożenie',
    r'\bthreats\b': 'zagrożenia',
    r'\bprotection\b': 'ochrona',
    r'\bprotect\b': 'chronić',
    r'\bprotected\b': 'chroniony',
    r'\bkeyword\b': 'słowo kluczowe',
    r'\bkeywords\b': 'słowa kluczowe',
    r'\bcommune\b': 'wspólnota',
    r'\bcommunion\b': 'komunia',
    r'\bcommunal\b': 'wspólny',
    r'\bcommunity\b': 'społeczność',
    r'\bcommunities\b': 'społeczności',
    r'\bsociety\b': 'społeczeństwo',
    r'\bsocial\b': 'społeczny',
    r'\bsociety\b': 'społeczeństwo',
    r'\bcollective\b': 'zbiorowe',
    r'\bcollection\b': 'zbiorowość',
    r'\bshaping\b': 'kształtowanie',
    r'\bshape\b': 'kształt',
    r'\bshaped\b': 'kształtowany',
    r'\breforma\b': 'reforma',
    r'\breform\b': 'zmiana',
    r'\breformed\b': 'zmieniony',
    r'\bpolitic\b': 'polityka',
    r'\bpolitical\b': 'politycz',
    r'\bpolitics\b': 'polityka',
    r'\bgovernment\b': 'rząd',
    r'\bgovernments\b': 'rządy',
    r'\bgovernance\b': 'zarządzanie',
    r'\bgovernor\b': 'gubernator',
    r'\badministration\b': 'administracja',
    r'\badministrative\b': 'administracyjny',
    r'\badministrator\b': 'administrator',
    r'\bauthority\b': 'autorytet',
    r'\bauthorities\b': 'autorytety',
    r'\bauthoritarian\b': 'autorytarny',
    r'\blog\b': 'dziennik',
    r'\blogs\b': 'dzienniki',
    r'\blog\b': 'log',
    r'\blogic\b': 'logika',
    r'\blogical\b': 'logiczny',
    r'\bfacts\b': 'fakty',
    r'\bfact\b': 'fakt',
    r'\banalysis\b': 'analiza',
    r'\banalyze\b': 'analizować',
    r'\banalyzed\b': 'przeanalizowany',
}

count = 0
for eng_pattern, pol_word in remaining.items():
    if re.search(eng_pattern, content, re.IGNORECASE):
        content = re.sub(eng_pattern, pol_word, content, flags=re.IGNORECASE | re.MULTILINE)
        count += 1

with open(filepath, 'w', encoding='utf-8') as f:
    f.write(content)

print(f"✅ Zastosowano {count} dodatkowych zamian")
print(f"📝 Plik: {filepath}")
print(f"✨ CZYSZCZENIE OSTATECZNE ZAKOŃCZONE")
