#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
ULTRA AGRESYWNA POLSZYZACJA - PASS 4
Konwersja 500+ angielskich wyrażeń na polski
"""

import re

FILE_PATH = r"c:\e-book-main\PUBLISHED_BOOK\Avatar_PinkMan_POLSKI.txt"

# Mega-słownik z 500+ wyrażeniami
ULTRA_TRANSLATIONS = {
    # PODSTAWOWE CZASOWNIKI I POMOCNICZE
    r"\bcan\b": "może",
    r"\bcan't\b": "nie może",
    r"\bcould\b": "mógłby",
    r"\bwill\b": "będzie",
    r"\bwould\b": "byłoby",
    r"\bshould\b": "powinien",
    r"\bmight\b": "mógłby",
    r"\bmust\b": "musi",
    r"\bhave to\b": "musi",
    r"\bhas to\b": "musi",
    r"\bhad to\b": "musiał",
    
    # CZASOWNIKI MODALOWE I POMOCNICZE
    r"\bwas\b": "był",
    r"\bwere\b": "było",
    r"\bbeen\b": "być",
    r"\bis\b": "jest",
    r"\bare\b": "są",
    r"\bam\b": "jestem",
    
    # CZASOWNIKI PRZEMIANY
    r"\bbecome\b": "staje się",
    r"\bbecomes\b": "staje się",
    r"\bbecoming\b": "stając się",
    r"\bbecame\b": "stał się",
    
    # ARTYKUŁY
    r"\bthe\b": "",
    r"\ba\b": "",
    r"\ban\b": "",
    
    # PRZYMIOTNIKI
    r"\bbeautiful\b": "piękny",
    r"\bbeautifully\b": "pięknie",
    r"\bdark\b": "ciemny",
    r"\bdarkly\b": "mroczni",
    r"\bgolden\b": "złoty",
    r"\bgeometric\b": "geometryczne",
    r"\bgeometrically\b": "geometrycznie",
    r"\bsomething\b": "coś",
    r"\bsomone\b": "ktoś",
    r"\bsomewhere\b": "gdzieś",
    r"\bnew\b": "nowy",
    r"\bnewer\b": "nowszy",
    r"\bold\b": "stary",
    r"\bolder\b": "starszy",
    r"\bhigh\b": "wysoki",
    r"\bhigher\b": "wyższy",
    r"\bdeep\b": "głębokie",
    r"\bdeeper\b": "głębsze",
    r"\bfresh\b": "świeży",
    r"\bwarm\b": "ciepły",
    r"\bcold\b": "zimny",
    r"\bgentile\b": "łagodny",
    r"\bgentle\b": "łagodny",
    r"\bgently\b": "łagodnie",
    r"\btruly\b": "rzeczywiście",
    r"\breal\b": "rzeczywisty",
    r"\breally\b": "rzeczywiście",
    r"\bethical\b": "etyczne",
    r"\bphysical\b": "fizyczne",
    r"\bperfect\b": "doskonały",
    r"\bperfectly\b": "doskonale",
    r"\bimmense\b": "ogromny",
    r"\bimmensely\b": "ogromnie",
    r"\bsimilar\b": "podobny",
    r"\bsimilarly\b": "podobnie",
    r"\bsuphisticated\b": "wyrafinowany",
    r"\bsophisticated\b": "wyrafinowany",
    r"\bintelligent\b": "inteligentny",
    r"\bintellectual\b": "intelektualny",
    r"\bintellectually\b": "intelektualnie",
    
    # PRZYSŁÓWKI I SPÓJNIKI
    r"\bthen\b": "wtedy",
    r"\bnow\b": "teraz",
    r"\btoday\b": "dzisiaj",
    r"\btomorrow\b": "jutro",
    r"\byesterday\b": "wczoraj",
    r"\bhere\b": "tutaj",
    r"\bthere\b": "tam",
    r"\bwhere\b": "gdzie",
    r"\bwhen\b": "kiedy",
    r"\bwhy\b": "dlaczego",
    r"\bhow\b": "jak",
    r"\bwhat\b": "co",
    r"\bwhich\b": "który",
    r"\bwho\b": "kto",
    r"\bwhom\b": "kogo",
    r"\bwhose\b": "czyj",
    r"\bif\b": "jeśli",
    r"\bassert\b": "twierdzi",
    r"\basserted\b": "twierdził",
    r"\basserts\b": "twierdzi",
    r"\bassure\b": "zapewnia",
    r"\bassured\b": "zapewnił",
    r"\bassures\b": "zapewnia",
    r"\bassuredly\b": "zapewniający",
    r"\bbut\b": "ale",
    r"\band\b": "i",
    r"\bor\b": "lub",
    r"\bnor\b": "ani",
    r"\byet\b": "jednak",
    r"\bso\b": "więc",
    r"\bbecause\b": "ponieważ",
    r"\btherefore\b": "dlatego",
    r"\bthus\b": "tym samym",
    r"\bhence\b": "stąd",
    r"\bmoreover\b": "ponadto",
    r"\bfurthermore\b": "ponadto",
    r"\bbesides\b": "oprócz",
    r"\binsead\b": "zamiast",
    r"\binstead\b": "zamiast",
    r"\binstead of\b": "zamiast",
    r"\bdespite\b": "mimo",
    r"\balthough\b": "choć",
    r"\bthough\b": "choć",
    r"\bwhile\b": "podczas gdy",
    r"\bwhereas\b": "podczas gdy",
    r"\btherefore\b": "w związku z tym",
    r"\bthroughout\b": "przez cały czas",
    r"\bcontinually\b": "ciągle",
    r"\bcontinuously\b": "ciągle",
    r"\bconstantly\b": "stale",
    r"\bever\b": "kiedykolwiek",
    r"\bnever\b": "nigdy",
    r"\balways\b": "zawsze",
    r"\boften\b": "często",
    r"\brarely\b": "rzadko",
    r"\bsometimes\b": "czasami",
    r"\boccasionally\b": "czasami",
    r"\bseldom\b": "rzadko",
    r"\balready\b": "już",
    r"\byet\b": "jeszcze",
    r"\bstill\b": "wciąż",
    r"\bjust\b": "właśnie",
    r"\bonly\b": "tylko",
    r"\beven\b": "nawet",
    r"\bvery\b": "bardzo",
    r"\bquite\b": "dość",
    r"\brather\b": "raczej",
    r"\bfully\b": "całkowicie",
    r"\bcompletely\b": "całkowicie",
    r"\bentirely\b": "całkowicie",
    r"\bwholly\b": "całkowicie",
    r"\babsolutely\b": "absolutnie",
    r"\bperfectly\b": "doskonale",
    r"\bexactly\b": "dokładnie",
    r"\bprecisely\b": "dokładnie",
    r"\baccurately\b": "dokładnie",
    r"\bcarefully\b": "ostrożnie",
    r"\bcautiously\b": "ostrożnie",
    r"\btentatively\b": "niepewnie",
    r"\btentative\b": "niepewny",
    r"\bslowly\b": "powoli",
    r"\bquickly\b": "szybko",
    r"\bfast\b": "szybko",
    r"\bclearly\b": "wyraźnie",
    r"\bobviously\b": "oczywiście",
    r"\bapparently\b": "najwyraźniej",
    r"\bseemingly\b": "najwyraźniej",
    r"\badmittedly\b": "przyznaje się",
    r"\bsurely\b": "na pewno",
    r"\bcertainly\b": "na pewno",
    r"\bprobably\b": "prawdopodobnie",
    r"\bpossibly\b": "możliwe",
    r"\bperhaps\b": "być może",
    r"\bmaybe\b": "być może",
    r"\blikely\b": "prawdopodobnie",
    r"\bunlikely\b": "nieprawdopodobnie",
    r"\bperhaps\b": "być może",
    r"\bapproximately\b": "około",
    r"\baround\b": "około",
    r"\bnearly\b": "niemal",
    r"\nalmost\b": "prawie",
    r"\balmostly\b": "prawie",
    r"\bpractically\b": "praktycznie",
    r"\bindeed\b": "rzeczywiście",
    r"\bcertainly\b": "na pewno",
    r"\bvery\b": "bardzo",
    r"\bquite\b": "dość",
    r"\brather\b": "raczej",
    r"\bsomewhat\b": "nieco",
    r"\bslightly\b": "nieco",
    r"\bfairly\b": "dość",
    r"\bsufficiently\b": "wystarczająco",
    r"\bfrequently\b": "często",
    
    # RZECZOWNIKI - PODSTAWOWE
    r"\bmen\b": "mężczyźni",
    r"\bman\b": "mężczyzna",
    r"\bwoman\b": "kobieta",
    r"\bwomen\b": "kobiety",
    r"\bchild\b": "dziecko",
    r"\bchildren\b": "dzieci",
    r"\bboy\b": "chłopiec",
    r"\bgirl\b": "dziewczyna",
    r"\bperson\b": "osoba",
    r"\bpeople\b": "ludzie",
    r"\bhuman\b": "człowiek",
    r"\bhumans\b": "ludzie",
    r"\blife\b": "życie",
    r"\blives\b": "żyje",
    r"\btime\b": "czas",
    r"\btimes\b": "czasy",
    r"\bday\b": "dzień",
    r"\bdays\b": "dni",
    r"\bnight\b": "noc",
    r"\bnights\b": "noce",
    r"\bworld\b": "świat",
    r"\bworlds\b": "światów",
    r"\buniverse\b": "wszechświat",
    r"\buniverses\b": "wszechświaty",
    r"\bgalaxy\b": "galaktyka",
    r"\bgalaxies\b": "galaktyki",
    r"\bstar\b": "gwiazda",
    r"\bstars\b": "gwiazdy",
    r"\bplanet\b": "planeta",
    r"\bplanets\b": "planety",
    r"\bsun\b": "słońce",
    r"\bmoon\b": "księżyc",
    r"\bsunrise\b": "wschód słońca",
    r"\bsunset\b": "zachód słońca",
    r"\blicht\b": "światło",
    r"\blightning\b": "błyskawica",
    r"\bshadow\b": "cień",
    r"\bshadows\b": "cienie",
    r"\bdarkness\b": "ciemność",
    r"\bsilence\b": "cisza",
    r"\bsound\b": "dźwięk",
    r"\bvoice\b": "głos",
    r"\bvoices\b": "głosy",
    r"\bword\b": "słowo",
    r"\bwords\b": "słowa",
    r"\blanguage\b": "język",
    r"\blanguages\b": "języki",
    r"\bmessage\b": "wiadomość",
    r"\bmessages\b": "wiadomości",
    r"\bquestion\b": "pytanie",
    r"\bquestions\b": "pytania",
    r"\banswer\b": "odpowiedź",
    r"\banswers\b": "odpowiedzi",
    r"\bthought\b": "myśl",
    r"\bthoughts\b": "myśli",
    r"\bidea\b": "idea",
    r"\bideas\b": "idee",
    r"\bbelief\b": "przekonanie",
    r"\bbeliefs\b": "przekonania",
    r"\bfaith\b": "wiara",
    r"\bhope\b": "nadzieja",
    r"\bfear\b": "strach",
    r"\blove\b": "miłość",
    r"\bhate\b": "nienawiść",
    r"\bjoy\b": "radość",
    r"\bsadness\b": "smutek",
    r"\bangst\b": "lęk",
    r"\banger\b": "gniew",
    r"\brave\b": "czartość",
    r"\bcourage\b": "odwaga",
    r"\bcowardice\b": "tchórzostwo",
    r"\bwisdom\b": "mądrość",
    r"\bfolly\b": "głupota",
    r"\bknowledge\b": "wiedza",
    r"\bignorance\b": "niewiedzą",
    r"\btruth\b": "prawda",
    r"\blie\b": "kłamstwo",
    r"\blies\b": "kłamstwa",
    r"\bdream\b": "sen",
    r"\bdreams\b": "sny",
    r"\breality\b": "rzeczywistość",
    r"\billusion\b": "iluzja",
    r"\billusions\b": "iluzje",
    
    # CZASOWNIKI - POSZERZONE
    r"\bthink\b": "myśli",
    r"\bthinks\b": "myśli",
    r"\bthinking\b": "myślenie",
    r"\bthought\b": "pomyślał",
    r"\bthinks\b": "myśli",
    r"\bknow\b": "wie",
    r"\bknows\b": "wie",
    r"\bknew\b": "wiedział",
    r"\bknowing\b": "wiedząc",
    r"\bunderstand\b": "rozumie",
    r"\bunderstand\b": "rozumie",
    r"\bunderstanding\b": "rozumienie",
    r"\bunderstood\b": "zrozumiał",
    r"\bfeel\b": "czuje",
    r"\bfeels\b": "czuje",
    r"\bfelt\b": "czuł",
    r"\bfeeling\b": "czucie",
    r"\bsee\b": "widzi",
    r"\bsees\b": "widzi",
    r"\bseeing\b": "widząc",
    r"\bsaw\b": "widział",
    r"\blook\b": "patrzy",
    r"\blooks\b": "patrzy",
    r"\blooked\b": "patrzył",
    r"\blooking\b": "patrząc",
    r"\bhear\b": "słyszy",
    r"\bhears\b": "słyszy",
    r"\bheard\b": "słyszał",
    r"\bhearing\b": "słyszenie",
    r"\bspeak\b": "mówi",
    r"\bspeaks\b": "mówi",
    r"\bspoke\b": "powiedział",
    r"\bspeaking\b": "mówiąc",
    r"\btalk\b": "rozmawia",
    r"\btalks\b": "rozmawia",
    r"\btalked\b": "rozmawiał",
    r"\btalking\b": "rozmawiając",
    r"\bsay\b": "mówi",
    r"\bsays\b": "mówi",
    r"\bsaid\b": "powiedział",
    r"\bsaying\b": "mówiąc",
    r"\bask\b": "pyta",
    r"\basked\b": "pytał",
    r"\basking\b": "pytając",
    r"\btell\b": "mówi",
    r"\btells\b": "mówi",
    r"\btold\b": "powiedział",
    r"\btelling\b": "mówiąc",
    r"\bwrite\b": "pisze",
    r"\bwrites\b": "pisze",
    r"\bwrote\b": "napisał",
    r"\bwriting\b": "pisząc",
    r"\bread\b": "czyta",
    r"\breads\b": "czyta",
    r"\breading\b": "czytając",
    r"\blisten\b": "słucha",
    r"\blistens\b": "słucha",
    r"\blistened\b": "słuchał",
    r"\blistening\b": "słuchając",
    r"\bwatch\b": "obserwuje",
    r"\bwatches\b": "obserwuje",
    r"\bwatched\b": "obserwował",
    r"\bwatching\b": "obserwując",
    r"\bwalk\b": "idzie",
    r"\bwalks\b": "idzie",
    r"\bwalked\b": "szedł",
    r"\bwalking\b": "idąc",
    r"\brun\b": "biegnie",
    r"\bruns\b": "biegnie",
    r"\bran\b": "biegł",
    r"\brunning\b": "biegnąc",
    r"\bjump\b": "skacze",
    r"\bjumps\b": "skacze",
    r"\bjumped\b": "skoczył",
    r"\bjumping\b": "skacząc",
    r"\bsit\b": "siedzi",
    r"\bsits\b": "siedzi",
    r"\bsat\b": "siedział",
    r"\bsitting\b": "siedząc",
    r"\bstand\b": "stoi",
    r"\bstands\b": "stoi",
    r"\bstood\b": "stał",
    r"\bstanding\b": "stojąc",
    r"\bgo\b": "idzie",
    r"\bgoes\b": "idzie",
    r"\bgoing\b": "idąc",
    r"\bgo\b": "poszedł",
    r"\bcome\b": "przychodzi",
    r"\bcomes\b": "przychodzi",
    r"\bcame\b": "przyszedł",
    r"\bcoming\b": "przychodząc",
    r"\barrive\b": "przybywa",
    r"\barrives\b": "przybywa",
    r"\barrived\b": "przybył",
    r"\barriving\b": "przybywa",
    r"\bleave\b": "opuszcza",
    r"\bleaves\b": "opuszcza",
    r"\bleft\b": "opuścił",
    r"\bleaving\b": "opuszczając",
    r"\bstay\b": "pozostaje",
    r"\bstays\b": "pozostaje",
    r"\bstayed\b": "pozostał",
    r"\bstaying\b": "pozostając",
    r"\bget\b": "dostaje",
    r"\bgets\b": "dostaje",
    r"\bgot\b": "dostał",
    r"\bgetting\b": "dostając",
    r"\btake\b": "bierze",
    r"\btakes\b": "bierze",
    r"\btook\b": "wziął",
    r"\btaking\b": "biorąc",
    r"\bgive\b": "daje",
    r"\bgives\b": "daje",
    r"\bgave\b": "dał",
    r"\bgiving\b": "dając",
    r"\bkeep\b": "trzyma",
    r"\bkeeps\b": "trzyma",
    r"\bkept\b": "trzymał",
    r"\bkeeping\b": "trzymając",
    r"\bfind\b": "znajduje",
    r"\bfinds\b": "znajduje",
    r"\bfound\b": "znalazł",
    r"\bfinding\b": "znajdując",
    r"\bseek\b": "szuka",
    r"\bseeks\b": "szuka",
    r"\bsought\b": "szukał",
    r"\bseeking\b": "szukając",
    r"\bsearch\b": "przeszukuje",
    r"\bsearches\b": "przeszukuje",
    r"\bsearched\b": "przeszukiwał",
    r"\bsearching\b": "przeszukując",
    r"\blook for\b": "szuka",
    r"\bhelp\b": "pomaga",
    r"\bhelps\b": "pomaga",
    r"\bhelped\b": "pomagał",
    r"\bhelping\b": "pomagając",
    r"\bstop\b": "zatrzymuje",
    r"\bstops\b": "zatrzymuje",
    r"\bstopped\b": "zatrzymał",
    r"\bstopping\b": "zatrzymując",
    r"\bstart\b": "zaczyna",
    r"\bstarts\b": "zaczyna",
    r"\bstarted\b": "zaczął",
    r"\bstarting\b": "zaczynając",
    r"\bbegin\b": "zaczyna",
    r"\bbegins\b": "zaczyna",
    r"\bbegun\b": "zaczęty",
    r"\bbeginning\b": "zaczynając",
    r"\bend\b": "kończy",
    r"\bends\b": "kończy",
    r"\bended\b": "skończył",
    r"\bending\b": "kończąc",
    r"\bfinish\b": "kończył",
    r"\bfinishes\b": "kończy",
    r"\bfinished\b": "skończył",
    r"\bfinishing\b": "kończąc",
    r"\bcontinue\b": "kontynuuje",
    r"\bcontinues\b": "kontynuuje",
    r"\bcontinued\b": "kontynuował",
    r"\bcontinuing\b": "kontynuując",
    r"\breturn\b": "wraca",
    r"\breturns\b": "wraca",
    r"\breturned\b": "wrócił",
    r"\breturning\b": "wracając",
    r"\benter\b": "wchodzi",
    r"\benters\b": "wchodzi",
    r"\bentered\b": "wszedł",
    r"\bentering\b": "wchodząc",
    r"\bexit\b": "wychodzi",
    r"\bexits\b": "wychodzi",
    r"\bexited\b": "wyszedł",
    r"\bexiting\b": "wychodząc",
    r"\bopen\b": "otwiera",
    r"\bopens\b": "otwiera",
    r"\bopened\b": "otworzył",
    r"\bopening\b": "otwierając",
    r"\bclose\b": "zamyka",
    r"\bcloses\b": "zamyka",
    r"\bclosed\b": "zamknął",
    r"\bclosing\b": "zamykając",
    r"\bdraw\b": "rysuje",
    r"\bdraws\b": "rysuje",
    r"\bdrew\b": "rysował",
    r"\bdrawing\b": "rysując",
    r"\bpaint\b": "maluje",
    r"\bpaints\b": "maluje",
    r"\bpainted\b": "malował",
    r"\bpainting\b": "malując",
    r"\buse\b": "używa",
    r"\buses\b": "używa",
    r"\bused\b": "używał",
    r"\busing\b": "używając",
    r"\bwork\b": "pracuje",
    r"\bworks\b": "pracuje",
    r"\bworked\b": "pracował",
    r"\bworking\b": "pracując",
    r"\bplay\b": "gra",
    r"\bplays\b": "gra",
    r"\bplayed\b": "grał",
    r"\bplaying\b": "grając",
    r"\bsing\b": "śpiewa",
    r"\bsings\b": "śpiewa",
    r"\bsang\b": "śpiewał",
    r"\bsinging\b": "śpiewając",
    r"\bdan\b": "tańczy",
    r"\bdance\b": "tańczy",
    r"\bdances\b": "tańczy",
    r"\bdanced\b": "tańczył",
    r"\bdancing\b": "tańcząc",
    r"\bstudy\b": "uczy się",
    r"\bstudies\b": "uczy się",
    r"\bstudied\b": "uczył się",
    r"\bstudying\b": "ucząc się",
    r"\bteach\b": "uczy",
    r"\bteaches\b": "uczy",
    r"\btaught\b": "uczył",
    r"\bteaching\b": "ucząc",
    r"\blearn\b": "uczy się",
    r"\blearns\b": "uczy się",
    r"\blearned\b": "nauczył się",
    r"\blearning\b": "ucząc się",
    r"\bcreat\b": "tworzy",
    r"\bcreate\b": "tworzy",
    r"\bcreates\b": "tworzy",
    r"\bcreated\b": "stworzył",
    r"\bcreating\b": "tworząc",
    r"\bdestroy\b": "niszczy",
    r"\bdestroys\b": "niszczy",
    r"\bdestroyed\b": "zniszczył",
    r"\bdestroying\b": "niszcząc",
    r"\bbreak\b": "łamie",
    r"\bbreaks\b": "łamie",
    r"\bbroke\b": "złamał",
    r"\bbreaking\b": "łamiąc",
    r"\brepair\b": "naprawia",
    r"\brepairs\b": "naprawia",
    r"\brepaired\b": "naprawił",
    r"\brepairing\b": "naprawiając",
    r"\bfix\b": "naprawia",
    r"\bfixes\b": "naprawia",
    r"\bfixed\b": "naprawił",
    r"\bfixing\b": "naprawiając",
    r"\bcook\b": "gotuje",
    r"\bcooks\b": "gotuje",
    r"\bcooked\b": "gotował",
    r"\bcooking\b": "gotując",
    r"\beat\b": "je",
    r"\beats\b": "je",
    r"\bate\b": "jadł",
    r"\beating\b": "jedząc",
    r"\bdrink\b": "pije",
    r"\bdrinks\b": "pije",
    r"\bdrank\b": "pił",
    r"\bdrinking\b": "pijąc",
    r"\bsleep\b": "śpi",
    r"\bsleeps\b": "śpi",
    r"\bslept\b": "spał",
    r"\bsleeping\b": "śpiąc",
    r"\bwake\b": "budzi się",
    r"\bwakes\b": "budzi się",
    r"\bwoke\b": "obudził się",
    r"\bwaking\b": "budząc się",
    r"\bawake\b": "budzi się",
    r"\bawaken\b": "budzi się",
    r"\bawakens\b": "budzi się",
    r"\bawakened\b": "obudził się",
    r"\bawakening\b": "budząc się",
    r"\bfight\b": "walczy",
    r"\bfights\b": "walczy",
    r"\bfought\b": "walczył",
    r"\bfighting\b": "walcząc",
    r"\bstuggle\b": "walczy",
    r"\bstruggles\b": "walczy",
    r"\bstruggled\b": "walczył",
    r"\bstruggling\b": "walcząc",
    r"\bwin\b": "wygrywa",
    r"\bwins\b": "wygrywa",
    r"\bwon\b": "wygrał",
    r"\bwinning\b": "wygrywając",
    r"\blose\b": "przegrywa",
    r"\bloses\b": "przegrywa",
    r"\blost\b": "przegrał",
    r"\blosing\b": "przegrywając",
    r"\bsucceed\b": "powiedzie się",
    r"\bsucceeds\b": "powiedzie się",
    r"\bsucceeded\b": "powiódł się",
    r"\bsucceeding\b": "powiedzie się",
    r"\bfail\b": "zawiedzie",
    r"\bfails\b": "zawiedzie",
    r"\bfailed\b": "zawiódł",
    r"\bfailing\b": "zawiedzenie",
    r"\btry\b": "próbuje",
    r"\btries\b": "próbuje",
    r"\btried\b": "próbował",
    r"\btrying\b": "próbując",
    r"\battempt\b": "próbuje",
    r"\battempts\b": "próbuje",
    r"\battempted\b": "próbował",
    r"\battempting\b": "próbując",
    r"\ballow\b": "pozwala",
    r"\ballows\b": "pozwala",
    r"\ballowed\b": "pozwolił",
    r"\ballowing\b": "pozwalając",
    r"\bpermit\b": "pozwala",
    r"\bpermits\b": "pozwala",
    r"\bpermitted\b": "pozwolił",
    r"\bpermitting\b": "pozwalając",
    r"\bprevent\b": "zapobiega",
    r"\bprevents\b": "zapobiega",
    r"\bprevented\b": "zapobiegł",
    r"\bpreventing\b": "zapobiegając",
    r"\bstop\b": "zatrzymuje",
    r"\bban\b": "zakazuje",
    r"\bbans\b": "zakazuje",
    r"\bbanned\b": "zakazał",
    r"\bbanning\b": "zakazując",
    r"\bforbid\b": "zakazuje",
    r"\bforbids\b": "zakazuje",
    r"\bforbidden\b": "zakazany",
    r"\bforbidding\b": "zakazując",
    r"\ballow\b": "pozwala",
    r"\braise\b": "podnosi",
    r"\braises\b": "podnosi",
    r"\braised\b": "podniósł",
    r"\braising\b": "podnosząc",
    r"\blower\b": "opuszcza",
    r"\blowers\b": "opuszcza",
    r"\blowered\b": "opuścił",
    r"\blowering\b": "opuszczając",
    r"\bcut\b": "tnie",
    r"\bcuts\b": "tnie",
    r"\bcut\b": "ciął",
    r"\bcutting\b": "tniąc",
    r"\bjoin\b": "łączy",
    r"\bjoins\b": "łączy",
    r"\bjoined\b": "połączył",
    r"\bjoining\b": "łącząc",
    r"\bseparate\b": "oddziela",
    r"\bseparates\b": "oddziela",
    r"\bseparated\b": "oddzielił",
    r"\bseparating\b": "oddzielając",
    r"\bsplit\b": "dzieli",
    r"\bsplits\b": "dzieli",
    r"\bsplit\b": "podzielił",
    r"\bsplitting\b": "dzieląc",
    r"\bunite\b": "jednoczy",
    r"\bunites\b": "jednoczy",
    r"\bunited\b": "zjednoczył",
    r"\buniting\b": "jednocząc",
    r"\bconnect\b": "łączy",
    r"\bconnects\b": "łączy",
    r"\bconnected\b": "połączył",
    r"\bconnecting\b": "łącząc",
    r"\bdisconnect\b": "rozłącza",
    r"\bdisconnects\b": "rozłącza",
    r"\bdisconnected\b": "rozłączył",
    r"\bdisconnecting\b": "rozłączając",
    r"\bgenerate\b": "generuje",
    r"\bgenerates\b": "generuje",
    r"\bgenerated\b": "wygenerował",
    r"\bgenerating\b": "generując",
    r"\bproduce\b": "produkuje",
    r"\bproduces\b": "produkuje",
    r"\bproduced\b": "wyprodukował",
    r"\bproducing\b": "produkując",
    r"\bconsume\b": "zużywa",
    r"\bconsumes\b": "zużywa",
    r"\bconsumed\b": "zużył",
    r"\bconsuming\b": "zużywając",
    r"\bexist\b": "istnieje",
    r"\bexists\b": "istnieje",
    r"\bexisted\b": "istniał",
    r"\bexisting\b": "istniejący",
    r"\bappear\b": "pojawia się",
    r"\bappears\b": "pojawia się",
    r"\bappeared\b": "pojawił się",
    r"\bappearing\b": "pojawiając się",
    r"\bvanish\b": "znika",
    r"\bvanishes\b": "znika",
    r"\bvanished\b": "zniknął",
    r"\bvanishing\b": "znikając",
    r"\bdisappear\b": "znika",
    r"\bdisappears\b": "znika",
    r"\bdisappeared\b": "zniknął",
    r"\bdisappearing\b": "znikając",
    r"\bsurface\b": "pojawia się",
    r"\bsurfaces\b": "pojawia się",
    r"\bsurfaced\b": "pojawił się",
    r"\bsurfacing\b": "pojawiając się",
    r"\bmerge\b": "łączy się",
    r"\bmerges\b": "łączy się",
    r"\bmerged\b": "połączył się",
    r"\bmerging\b": "łącząc się",
    r"\bswallow\b": "pochłania",
    r"\bswallows\b": "pochłania",
    r"\bswallowed\b": "pochłonął",
    r"\bswallowing\b": "pochłaniając",
    r"\bexplode\b": "wybucha",
    r"\bexplodes\b": "wybucha",
    r"\bexploded\b": "wybuchł",
    r"\bexploding\b": "wybuchając",
    r"\bflare\b": "błyska",
    r"\bflares\b": "błyska",
    r"\bflared\b": "błysnął",
    r"\bflaring\b": "błyszcząc",
    r"\bshift\b": "przesuwa",
    r"\bshifts\b": "przesuwa",
    r"\bshifted\b": "przesunął",
    r"\bshifting\b": "przesuwając",
    r"\bpulse\b": "pulsuje",
    r"\bpulses\b": "pulsuje",
    r"\bpulsed\b": "pulsował",
    r"\bpulsing\b": "pulsując",
    r"\bripple\b": "faluje",
    r"\bripples\b": "faluje",
    r"\brippled\b": "falował",
    r"\brippling\b": "falując",
    r"\bflow\b": "płynie",
    r"\bflows\b": "płynie",
    r"\bflowed\b": "płynął",
    r"\bflowing\b": "płynąc",
    r"\bstream\b": "strumień",
    r"\bstreams\b": "strumienie",
    r"\bstreamed\b": "płynął",
    r"\bstreaming\b": "płynąc",
    r"\bsweep\b": "miotła",
    r"\bsweeps\b": "miotła",
    r"\bswept\b": "zamiotł",
    r"\bsweeping\b": "miotąc",
    r"\bspin\b": "wiruje",
    r"\bspins\b": "wiruje",
    r"\bspun\b": "wirował",
    r"\bspinning\b": "wirując",
    r"\brotate\b": "obraca się",
    r"\brotates\b": "obraca się",
    r"\brotated\b": "obrócił się",
    r"\brotating\b": "obracając się",
    r"\btwist\b": "skręca",
    r"\btwists\b": "skręca",
    r"\btwisted\b": "skręcił",
    r"\btwisting\b": "skręcając",
    r"\bturn\b": "obraca",
    r"\bturns\b": "obraca",
    r"\bturned\b": "obrócił",
    r"\bturning\b": "obracając",
    r"\bbend\b": "zgina",
    r"\bbends\b": "zgina",
    r"\bbent\b": "zginał",
    r"\bbending\b": "zginając",
    r"\bstretch\b": "rozciąga",
    r"\bstretches\b": "rozciąga",
    r"\bstretched\b": "rozciągnął",
    r"\bstretching\b": "rozciągając",
    r"\bshrink\b": "kurczy",
    r"\bshrinks\b": "kurczy",
    r"\bshrank\b": "kurczył",
    r"\bshrinking\b": "kurczując",
    r"\bexpand\b": "rozszerza",
    r"\bexpands\b": "rozszerza",
    r"\bexpanded\b": "rozszerzył",
    r"\bexpanding\b": "rozszerzając",
    r"\bgrow\b": "rośnie",
    r"\bgrows\b": "rośnie",
    r"\bgrew\b": "rósł",
    r"\bgrowing\b": "rosnąc",
    r"\bshrivel\b": "kurczy się",
    r"\bshrivels\b": "kurczy się",
    r"\bshriveled\b": "skurczył się",
    r"\bshriveling\b": "kurczując się",
    r"\bwither\b": "więdnie",
    r"\bwithers\b": "więdnie",
    r"\bwithered\b": "zwiędł",
    r"\bwithering\b": "więdnąc",
    r"\bblossom\b": "rozkwita",
    r"\bblossoms\b": "rozkwita",
    r"\bblossomed\b": "rozkwitł",
    r"\bblossoming\b": "rozkwitając",
    r"\bflourish\b": "rozkwita",
    r"\bflourishes\b": "rozkwita",
    r"\bflourished\b": "rozkwitł",
    r"\bflourishing\b": "rozkwitając",
    r"\bdecay\b": "rozkłada",
    r"\bdecays\b": "rozkłada",
    r"\bdecayed\b": "rozkładał",
    r"\bdecaying\b": "rozkładając",
    r"\brot\b": "gnijnie",
    r"\brots\b": "gnijnie",
    r"\brotted\b": "gnił",
    r"\brotting\b": "gniąc",
    r"\bpurify\b": "oczyszcza",
    r"\bpurifies\b": "oczyszcza",
    r"\bpurified\b": "oczyścił",
    r"\bpurifying\b": "oczyszczając",
    r"\bcontaminate\b": "zanieczyszcza",
    r"\bcontaminates\b": "zanieczyszcza",
    r"\bcontaminated\b": "zanieczyszczył",
    r"\bcontaminating\b": "zanieczyszczając",
    r"\binfect\b": "zakaża",
    r"\binfects\b": "zakaża",
    r"\binfected\b": "zakaził",
    r"\binfecting\b": "zakazując",
    r"\bheal\b": "leczy",
    r"\bheals\b": "leczy",
    r"\bhealed\b": "leczył",
    r"\bhealing\b": "leczy",
    r"\bsuffer\b": "cierpi",
    r"\bsuffers\b": "cierpi",
    r"\bsuffered\b": "cierpieł",
    r"\bsuffering\b": "cierpiąc",
    r"\bpain\b": "boli",
    r"\bpains\b": "boli",
    r"\bpained\b": "bolało",
    r"\bpaining\b": "bolący",
    r"\bache\b": "boli",
    r"\baches\b": "boli",
    r"\bached\b": "bolało",
    r"\baching\b": "bolący",
    r"\bcomfort\b": "wygoda",
    r"\bcomforts\b": "wygoda",
    r"\bcomforted\b": "wygodny",
    r"\bcomforting\b": "wygodny",
    r"\brefresh\b": "oświeża",
    r"\brefreshes\b": "oświeża",
    r"\brefreshed\b": "oświeżył",
    r"\brefreshing\b": "oświeżający",
    r"\brelax\b": "relaksuje",
    r"\brelaxes\b": "relaksuje",
    r"\brelaxed\b": "zrelaksował",
    r"\brelaxing\b": "relaksujący",
    r"\bstress\b": "stres",
    r"\bstresses\b": "stres",
    r"\bstressed\b": "zestresowany",
    r"\bstressing\b": "stresujący",
    r"\btense\b": "napięty",
    r"\btenses\b": "napięty",
    r"\btensed\b": "napięty",
    r"\btensing\b": "napięty",
    r"\bcalm\b": "uspokaja",
    r"\bcalms\b": "uspokaja",
    r"\bcalmed\b": "uspokojony",
    r"\bcalming\b": "uspokajający",
    r"\bsoothe\b": "uspokaja",
    r"\bsoothes\b": "uspokaja",
    r"\bsoothed\b": "uspokojony",
    r"\bsoothing\b": "uspokajający",
    r"\btroubl\b": "kłopotliwy",
    r"\btrouble\b": "kłopotliwy",
    r"\btroubles\b": "kłopotliwy",
    r"\btroubled\b": "kłopotliwy",
    r"\btro\b": "cierpieć",
    r"\bdisturb\b": "niepokoi",
    r"\bdisturbs\b": "niepokoi",
    r"\bdisturbed\b": "zaniepokojony",
    r"\bdisturbing\b": "niepokojący",
    r"\bupset\b": "denerwuje",
    r"\bupsets\b": "denerwuje",
    r"\bupset\b": "zdenerwowany",
    r"\bupsetting\b": "denerwujący",
    r"\bfrustrate\b": "frustruje",
    r"\bfrustraes\b": "frustruje",
    r"\bfrustrated\b": "sfrustowany",
    r"\bfrustrating\b": "frustrujący",
    r"\bconfuse\b": "myli",
    r"\bconfuses\b": "myli",
    r"\bconfused\b": "poplątany",
    r"\bconfusing\b": "mylący",
    r"\bclarity\b": "jasność",
    r"\bclarify\b": "wyjaśnia",
    r"\bclarifies\b": "wyjaśnia",
    r"\bclarified\b": "wyjaśnił",
    r"\bclarifying\b": "wyjaśniając",
    r"\bobscure\b": "zaciemnia",
    r"\bobscures\b": "zaciemnia",
    r"\bobscured\b": "zaciemniony",
    r"\bobscuring\b": "zaciemniając",
    r"\bhide\b": "ukrywa",
    r"\bhides\b": "ukrywa",
    r"\bhid\b": "ukrył",
    r"\bhiding\b": "ukrywając",
    r"\breveal\b": "odkrywa",
    r"\breveals\b": "odkrywa",
    r"\brevealed\b": "odkrył",
    r"\brevealing\b": "odkrywając",
    r"\bexpose\b": "odsłania",
    r"\bexposes\b": "odsłania",
    r"\bexposed\b": "odsłonięty",
    r"\bexposing\b": "odsłaniając",
    r"\bcover\b": "zakrywa",
    r"\bcovers\b": "zakrywa",
    r"\bcovered\b": "zakryty",
    r"\bcovering\b": "zakrywając",
    r"\buncover\b": "odkrywa",
    r"\buncoverss\b": "odkrywa",
    r"\buncovered\b": "odkryty",
    r"\buncovering\b": "odkrywając",
    r"\bmanifest\b": "objawia",
    r"\bmanifests\b": "objawia",
    r"\bmanifested\b": "objawiony",
    r"\bmanifesting\b": "objawia",
    r"\bmaterialize\b": "materializuje",
    r"\bmaterializes\b": "materializuje",
    r"\bmaterialized\b": "zmaterializował",
    r"\bmaterializing\b": "materializując",
    r"\btransmute\b": "transmutuje",
    r"\btransmutes\b": "transmutuje",
    r"\btransmuted\b": "transmutował",
    r"\btransmuting\b": "transmutując",
    r"\btransform\b": "transformuje",
    r"\btransforms\b": "transformuje",
    r"\btransformed\b": "transformował",
    r"\btransforming\b": "transformując",
    r"\brevolutonalize\b": "rewolucjonizuje",
    r"\brevolutionize\b": "rewolucjonizuje",
    r"\brevolutionizes\b": "rewolucjonizuje",
    r"\brevolutionized\b": "rewolucjonizował",
    r"\brevolutionizing\b": "rewolucjonizując",
    r"\beveryworm\b": "każdy",
    
    # PREPOSYCJE
    r"\bin\b": "w",
    r"\bon\b": "na",
    r"\bat\b": "w",
    r"\bby\b": "przez",
    r"\bfrom\b": "z",
    r"\bto\b": "do",
    r"\bfor\b": "dla",
    r"\bwith\b": "z",
    r"\bwitout\b": "bez",
    r"\bwithout\b": "bez",
    r"\bagainst\b": "przeciwko",
    r"\bamong\b": "pośród",
    r"\bamongst\b": "pośród",
    r"\bbetween\b": "między",
    r"\bthrough\b": "przez",
    r"\bthroughout\b": "przez cały",
    r"\bbefore\b": "przed",
    r"\bafter\b": "po",
    r"\babove\b": "powyżej",
    r"\bbelow\b": "poniżej",
    r"\bunder\b": "pod",
    r"\bover\b": "nad",
    r"\buncer\b": "pod",
    r"\binside\b": "wewnątrz",
    r"\boutside\b": "na zewnątrz",
    r"\baround\b": "wokół",
    r"\binto\b": "do",
    r"\bout of\b": "z",
    r"\boff\b": "poza",
    r"\btowards\b": "w kierunku",
    r"\btoward\b": "w kierunku",
    r"\baway from\b": "z dala od",
    r"\baway\b": "daleko",
    r"\bupstairs\b": "na górze",
    r"\bdownstairs\b": "na dole",
    r"\bupfront\b": "z przodu",
    r"\bbackward\b": "do tyłu",
    r"\bbackwards\b": "do tyłu",
    r"\bforward\b": "do przodu",
    r"\bsideway\b": "na bok",
    r"\bsideways\b": "na bok",
    r"\baside\b": "na bok",
    r"\balong\b": "wzdłuż",
    r"\balongside\b": "obok",
    r"\bpast\b": "obok",
    r"\bnear\b": "blisko",
    r"\bnearby\b": "blisko",
    r"\bcross\b": "poprzez",
    r"\bacross\b": "przez",
    r"\bwithin\b": "w obrębie",
    r"\bfrom..to\b": "z...do",
    r"\bfrom..\b": "z..",
    r"\bexcept\b": "oprócz",
    r"\bexcluding\b": "z wyłączeniem",
    r"\bincluding\b": "obejmujący",
    r"\balong with\b": "wraz z",
    r"\baccording to\b": "według",
    r"\bowing to\b": "na skutek",
    r"\bdue to\b": "z powodu",
    r"\bbecause of\b": "z powodu",
    r"\bas a result of\b": "w wyniku",
    r"\bin spite of\b": "mimo",
    r"\bnotwithstanding\b": "mimo",
    r"\bcontrary to\b": "wbrew",
    r"\bagainst\b": "przeciwko",
    r"\bin favor of\b": "na korzyść",
    r"\bin front of\b": "przed",
    r"\bbehind\b": "za",
    r"\baside from\b": "poza",
    r"\bapart from\b": "poza",
    r"\binstead of\b": "zamiast",
    r"\brather than\b": "raczej niż",
    r"\bsuch as\b": "takie jak",
    r"\blike\b": "jak",
    r"\bunlike\b": "w odróżnieniu od",
    r"\btypical of\b": "typowe dla",
    r"\batypical of\b": "atypowe dla",
}

with open(FILE_PATH, 'r', encoding='utf-8') as f:
    content = f.read()

original_size = len(content)

for english, polish in ULTRA_TRANSLATIONS.items():
    content = re.sub(english, polish, content, flags=re.IGNORECASE)

with open(FILE_PATH, 'w', encoding='utf-8') as f:
    f.write(content)

print("🔄 Zastosowywanie ultra-mega-słownika polszyzacyjnego...")
print("✅ POLSZYZACJA ULTRA-PASS DOKOŃCZONA!")
print(f"📊 Zamienionych wyrażeń: {len(ULTRA_TRANSLATIONS)}")
print(f"📁 Plik: {FILE_PATH}")
print(f"📈 Rozmiaz: {original_size} → {len(content)} znaków")
